#ifndef MOD_SECONDARY_CLASS_LOADER_H
#define MOD_SECONDARY_CLASS_LOADER_H

// Entry point generated by AC_ADD_SCRIPT_LOADER("mod_secondary_class", ...).
// ModulesLoader.cpp declares + calls Addmod_secondary_classScripts().
void Addmod_secondary_classScripts();

#endif
